---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r cars}
# http://www.sumsar.net/blog/2016/06/how-to-cut-your-planks-with-r/
planks_we_have <- c(120, 137, 220, 420, 480)
planks_we_want <- c(19, 19, 19, 19, 79, 79, 79, 103, 103,
                    103, 135, 135, 135, 135, 160)

library(adagio)
# mknapsack calling signature is: mknapsack(values, weights, capacities)
solution <- mknapsack(planks_we_want, 
                      planks_we_want, 
                      planks_we_have)
# Above I added +1 cm  to each length to compensate for the loss when sawing.
solution$ksack

assignment <- data.frame(
  cut_this = planks_we_have[solution$ksack],
  into_this = planks_we_want)
t(assignment[order(assignment[,1]), ])

#-----------------------

# total hours per day in all rooms
hours_per_day_we_have <- 
  c(100, 110) 

# hours for each session 
hours_per_session_we_want <- 
  c(11, 21, 31, 41, 51) 

library(adagio)
# mknapsack calling signature is: mknapsack(values, weights, capacities)
solution <- mknapsack(hours_per_session_we_want, 
                      hours_per_session_we_want, 
                      hours_per_day_we_have)
# Above I added +1 cm  to each length to compensate for the loss when sawing.
solution$ksack

assignment <- data.frame(
  into_this = hours_per_day_we_have[solution$ksack],
  put_this = hours_per_session_we_want)
t(assignment[order(assignment[,1]), ])

#----------------------


# one day at a time
# rooms by hours
big <- c(4001, 4002)
big
sum(big)

small <- c(1.00, 2.00, 1.50, 3.0) * 1000
small
sum(small)

library(adagio)
# mknapsack calling signature is: mknapsack(values, weights, capacities)
solution <- mknapsack(small, 
                      small, 
                      big)

{
assignment <- data.frame(
  into_this = big[solution$ksack],
  put_this = small)
t(assignment[order(assignment[,1]), ])
}




```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
